### ISSUE TITLE
Image Lab freeze

### ISSUE THREAD

**Issue by ccason1** [MetroCS/imagelab#10]
**Describe the bug**
When I open an image display window and press "play", the program plays music, but all of the program's buttons become unresponsive. To close the program, I had to close it manually from a command line.

**To Reproduce**
1. Run ImageLab.jar
2. Click on File, Open
3. Double click on a picture in file system
4. Click on File, Play (on either window--both buttons freeze the program)

**Expected behavior**
Upon running through the steps above buttons should remain responsive.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jody** [comment]
This is working as designed.
Please create a User Story for a change/enhancement rather than a bug report.
