### ISSUE TITLE
[UserStory] Provide a Code of Conduct for this project

### ISSUE THREAD

**Issue by jody** [MetroCS/imagelab#116]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _contributor or potential contributor_  
**I want**  _to view a contributor code of conduct_  
**so that**  _I am aware of the responsibilities of a contributor._  

## Acceptance Criteria

* A "Contributor Code of Conduct" document exists in the repository and is linked to from the README.md.
* The dependent issue contains information about linking to the new code of conduct document

## Supporting Information
* Example [Development Conventions](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/DevelopmentConventions.md)

### Depends On
_(Issues on which this story depends)_
### Dependents
* #24

**Comment by jody** [comment]
@ramahali I've created this issue as a dependency for issue #24
Please review to see if this is what you are expecting to work on.

**Comment by CamiJolly1** [comment]
I an helping with the technical writting of this issue, can you please add me as well?

**Comment by KaizenPool** [comment]
please assign this to mean

**Comment by jody** [comment]
PR #125 closes this issue.
