### ISSUE TITLE
[UserStory] ReadMe updates from a Developer perspective. 

### ISSUE THREAD

**Issue by ematteso** [MetroCS/imagelab#118]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** developer  
**I want**  I want to be able to learn how to build the product
**so that**  I can make appropriate contributions to the project

## Acceptance Criteria
ReadMe supports both new and returning developers with respect to building, testing, modifying, and contributing to the project.

1. There is a Table of Contents directory with links to sections
2. The information about product building includes the following information, ordered appropriately for developers:
-> Build System Requirements
-> Creating an executable jar
-> Use of Gradle (and/or other resources)

## Supporting Information
At current, the instructions for install are out of order. Gradle must be installed first before you can create an executable jar or compile and run from the command line, these steps should directly follow gradle install. Resources for gradle use should be below the instructions required to install / build / run the project locally.

### Dependents
#113

**Comment by jody** [comment]
I think this is now closed (via PR #120).
