### ISSUE TITLE
[UserStory] building graddle

### ISSUE THREAD

**Issue by KaizenPool** [MetroCS/imagelab#121]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  contributor 
**I want**  to know how and why to build the projecy
**so that** I can build the and edit the code on my computer

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* The build tool must work
* There is explanation about how it works 

### Scenario 1
When using the program on my own computer I can run java, but I cannot get the product to build. I would like to know how to build the program on my machine.

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
The title doesn't describe the issue.
The scenario indicates that this is an attempt to report a bug in the product, project, or project documentation.
### Action Requested
Please create a new issue using the "Bug report" template and provide the information needed to identify and reproduce the erroneous behavior.
