### ISSUE TITLE
[UserStory] Creating documentation for new contributors (Contribution file) 

### ISSUE THREAD

**Issue by CamiJolly1** [MetroCS/imagelab#132]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  contributor 
**I want**  documentation 
**so that**  new contributors know where they can get started and how they are able to contribute. 

## Acceptance Criteria
* A "Contribution file" document exists in the repository and is linked to from the README.md.

## Supporting Information
There is little documentation for ImageLab. It would be beneficial to new contributors to have documentation other than the README to know how and where to get started. Styling can also be included in the contribution file.

**Comment by jody** [comment]
Addressed by #136
