### ISSUE TITLE
[UserStory] Add a package-info.java file to the repository

### ISSUE THREAD

**Issue by alope151** [MetroCS/imagelab#15]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a maintainer
I want a file for package level documentation  
So that documentation is easy for maintainers to access.

## Acceptance Criteria
* Files providing package-level documentation that adhere to standard Javadoc conventions are present for _each_ package in the product.

**Comment by mbamiluka** [comment]
Assignable to @mbamiluka

**Comment by GOKU900** [comment]
I would like to be assigned to this issue.
