### ISSUE TITLE
[UserStory] Unit Test for ImgProvider

### ISSUE THREAD

**Issue by DendeLime** [MetroCS/imagelab#16]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_  
**I want**  _a unit test for the ImgProvider class_  
**so that**  _I can test the stability of the code_  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

1. Unit Test covers 85% of executable code within ImgProvider.java
2. Includes documentation for maintainers describing how to run and interpret tests

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
[Add unit tests for existing classes](https://github.com/MetroCS/imagelab/issues/4)

**Comment by corywilson88** [comment]
I would like to be assigned this issue.

**Comment by Jacobjfiske** [comment]
I would like to be assigned to this issue

**Comment by jody** [comment]
If not progress reported on this issue within 48 hours, will unassign.
