### ISSUE TITLE
[UserStory] UI change to initial window to show name and version of product

### ISSUE THREAD

**Issue by jody** [MetroCS/imagelab#22]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _{student, educator}_  
**I want**  _the initial UI window to include the name and version of the product_  
**so that**  _I have the product and version validated on startup_  

## Acceptance Criteria

* _Initial (opening) window displays the name and version of the product._

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_

### Dependents
_(Issues dependent on this story)_

**Comment by StilianB** [comment]
I would like to be added to this issue, please. @jody

**Comment by GOKU900** [comment]
I believe the program already shows the name and version in the initial UI window. 

![image](https://user-images.githubusercontent.com/69365600/96819010-e4ab5300-13df-11eb-9c2c-5512786f8d09.png)

**Comment by jody** [comment]
Thank you for reviewing and validating this!
Especially appreciate the included image.
The issue appears to have been addressed.
Will close this issue.
