### ISSUE TITLE
[UserStory] Provide documentation for contributors (including a code of conduct)

### ISSUE THREAD

**Issue by jody** [MetroCS/imagelab#24]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _contributor or potential contributor_  
**I want**  _documentation of how to contribute (including a contributor code of conduct)_  
**so that**  _I am aware of how to contribute and responsibilities of a contributor._  

## Acceptance Criteria

* A document exists in the repository, and linked from the website, that
  * gives an overview suitable for potential contributors
  * identifies project development technologies, tools, and conventions
  * explains the project repository organization
  * provides navigation to more specific documents
* A "Contributor Code of Conduct" document exists in the repository and is linked to from appropriate other documents, including the contribution overview. 

## Supporting Information
* Example [Contributor Code of Conduct](https://github.com/MetroCS/redistricting/blob/master/CODE_OF_CONDUCT.md)
* Example [Development Conventions](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/DevelopmentConventions.md)

### Depends On
* #116 
### Dependents
_(Issues dependent on this story)_

**Comment by ramahali** [comment]
I would like to work on Contributor Covenant Code of Conduct issue.

**Comment by jody** [comment]
Sounds good. Since that is only one part of this issue, I will open a new issue as a dependency for this issue. Once that has been created, I'll assign you to that new issue.

**Comment by jody** [comment]
@ramahali I've created the dependent issue #116
Please review the issue to see if it meets with your expectations.
You will need to add a request to be assigned to that issue as a comment before I can assign it to you.
