### ISSUE TITLE
[UserStory] Update build documentation to explain how to create the executable jar

### ISSUE THREAD

**Issue by jody** [MetroCS/imagelab#3]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  {maintainer, educator}  
**I want**  documentation that explains how to create an executable jar from the source  
**so that**  I can create an updated executable jar file of imagelab for my students to use.  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Project documentation includes build instructions that result in an executable jar.
* The executable jar created embodies the imageLab software and will invoke the appropriate main class to initialize and run imagelab.

## Supporting Information
https://bluej.org/tutorial/tutorial-v4.pdf - See section **8 Creating stand-alone applications**

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by entrylevelcs** [comment]
I would like to claim this issue.

**Comment by brianharrity** [comment]
@jody  Can I be assigned this issue?

**Comment by jody** [comment]
Are both @entrylevelcs and @brianharrity members of the same team?

**Comment by entrylevelcs** [comment]
No we are from different teams, I am with groupware.
