### ISSUE TITLE
[UserStory] _Project needs build instructions and supporting documentation_

### ISSUE THREAD

**Issue by jody** [MetroCS/imagelab#31]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _{developer | maintainer}_  
**I want**  _information about how to build the product_  
**so that**  _I can modify the product for my own use and as contribution to the project_  

## Acceptance Criteria

* _Steps to build the product are clearly stated and readily located in the repository_
* _Project conventions are clearly stated and readily located in the repository_

## Supporting Information
_See similar MetroCS projects:_
* [Redistricting](https://github.com/MetroCS/redistricting)
  * [Redistricting - Contributing](https://github.com/MetroCS/redistricting/blob/master/Contributing.md)
  * [Redistricting - Development Conventions](https://github.com/MetroCS/redistricting/blob/master/DevelopmentConventions.md)
* [Quality Tools for BlueJ](https://github.com/MetroCS/QualityToolsForBlueJ)
   * [QT4BJ Development Conventions](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/DevelopmentConventions.md)

## Related Issues
User Story #24

**Comment by nicolewelch** [comment]
Our team, coding collaborative, would like to claim this issue
kweidner14
rdaniel58
MetalEng
chrisreylo73

**Comment by jody** [comment]
I'm not positive, but I think that anyone who would also liked to be assigned to this issue just needs to make a comment from their own account.  (GitHub won't allow me to assign any account that hasn't already shown interest... which is a policy that makes sense.)

**Comment by jody** [comment]
This issue seems related to issue #3

**Comment by chrisreylo73** [comment]
Can you elaborate on what you mean by "Project Conventions"? 
Our Team is a little confused on what that means.

**Comment by jody** [comment]
> Can you elaborate on what you mean by "Project Conventions"?
I am referring to information similar to that which is linked to in the **Supporting Information** section of this issue.
Do you have a more specific question about those examples?
