### ISSUE TITLE
[UserStory] filters package checkstlye report

### ISSUE THREAD

**Issue by GeoffZC** [MetroCS/imagelab#35]
# User Story
### Essential components
- [X] Title describes the story
- [X] Stakeholder type is identified
- [X] Outcome is described
- [X] Rationale is explicit
- [X] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** contributor
**I want** the checkstyle errors in the filters package to be fixed
**so that** the code adheres to coding style conventions. 

## Acceptance Criteria
Checkstyle report for filters package has no checkstyle errors.

*Zero checkstyle errors for the filters package.
*Full JavaDoc documentation in filters package.
*Build runs without checkstyle errors.

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
Issue #32 dependent on completion of this issue.

**Comment by jody** [comment]
The file attachment (main.zip) isn't viewable in GitHub and there's no context explaining what that file is or why it is there.

**Comment by jody** [comment]
I think this is part of an epic, so that "parent" issue should be identified (probably as a Dependent).

**Comment by jody** [comment]
Since this specifically mentions "filters" in the heading, the body of the User Story (e.g., Outcome, Acceptance Criteria) should likewise reference the "filters" package.

**Comment by nlaratta** [comment]
I'd like to be assigned to this issue

**Comment by robo-jones** [comment]
I believe that the current project build meets the intention of all acceptance criteria for this user story; checkstyle reports no errors in the filters package, and each class in the package has appropriate javadoc comments. The third acceptance criteria, "Build runs without checkstyle errors" is not only beyond the scope of this specific issue (as there are other packages in the project), but is also contrary to the newly revised issue #32 which states that "TODO" checkstyle 'errors' are acceptable.

As such, I believe that this issue can be closed.

**Comment by jody** [comment]
Great!  Thank you for verifying the acceptance criteria!
