### ISSUE TITLE
[UserStory] Open another picture while audio is playing

### ISSUE THREAD

**Issue by seboss123** [MetroCS/imagelab#36]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  user of the image lab program
**I want**  to be able to open another picture while audio for a separate picture is playing
**so that**  I can view multiple pictures while audio is playing.

### Scenario 1
**Given**  User has opened an image in the product   
**when**  the user selects `Play` from the `File` menu of that image window's menu bar   
**then**  the user is still able to select `Open` from the` File` menu of the imagelab window

### Depends On
Issue #13

**Comment by jody** [comment]
Clarifications made to Acceptance Criteria.

**Comment by jody** [comment]
Is this addressed by PR #27 ?

**Comment by seboss123** [comment]
Yes. This issue has been resolved by PR #27
