### ISSUE TITLE
[UserStory]  Build existing source code files with Gradle

### ISSUE THREAD

**Issue by GracchusMinor** [MetroCS/imagelab#5]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer  
**I want**  an initial build file using Gradle
**so that**  I can run unit testing and code analysis tools

## Acceptance Criteria

* All existing source code files compile
* Retains functionality with javac command-line build
* Retains functionality with BlueJ
* Allows for future expansion
* Build file uses Gradle

## Supporting Information
_(Relevant information, context, resources)_

**Comment by jody** [comment]
Note that the acceptance criteria doesn't indicate anything related to Gradle. 👎

**Comment by GracchusMinor** [comment]
Fixed the glaring oversight. 

Also, can this user story be assigned to our team: Efficient-Software-Hypothesis 
Members: jstelka, GracchusMinor, DendeLime, BlackCanyonDreams, TImmyTurner123

**Comment by jstrelka** [comment]
Please assign the following team and its members to this issue:
@MetroCS/efficientsoftwarehypothesis 
@jstrelka 
@GracchusMinor 
@TImmyTurner123 
@BlackCanyonDreams 
@DendeLime 

Thanks!

**Comment by jody** [comment]
In addition to running unit testing and code analysis tools, it would be useful for the Gradle "run" task to ensure all components, including filters, are compiled according to ImageLab expectations (convention) and are thus available to the ImageLab application.

**Comment by jody** [comment]
Does not yet produce appropriate `imageLab.jar` file (see project [README](../blob/master/README.md)).

Needs documentation that explains both _how_ and _why_ this Gradle build's outcomes differ from the standard Java compilation ([javac](https://docs.oracle.com/en/java/javase/12/tools/javac.html)) build.

**Comment by jstrelka** [comment]
Please move issue to completed lane.
