### ISSUE TITLE
[UserStory] Ability to save audio the program generates

### ISSUE THREAD

**Issue by Codyhintzch** [MetroCS/imagelab#65]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As an** Imagelab user
**I want**  to be able to save the audio generated by the program
**so that**  I can save the audio as a media/audio file format

## Acceptance Criteria
When the program is used to generate audio from an image it provides the option to save the audio to a file that can be played later from any well known operating system

### Scenario 1
**Given** a user selects **file > play** from an image
**when** audio has been generated using a filter
**then** the user is able to save the generated audio to an audio file

**Comment by jody** [comment]
**Missing acceptance criteria.**

Also:
- Please modify the title to describe the change that is needed.
- The rationale presumes that the person running the program is generating the music, whereas we might better consider the programmer or the program itself to be doing the music generation. Please provide a more appropriately stated rationale.
