### ISSUE TITLE
[User Story] Halting of Music After the Image has Been Closed or a New Image is Played

### ISSUE THREAD

**Issue by Kelzihar** [MetroCS/imagelab#73]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _user_  
**I want**  _the image's music to stop when an image is closed or a different image is played_  
**so that**  _only one image's music plays at a time and cannot overlap each other_  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _When using file -> close | if the image that was closed had music playing, the music halts or stops_
* _When using file -> play | when two different images are up, if music is already playing from one image, the music currently playing halts and the most recent play starts as the only music occurring_
* _When using file -> play | multiple times on one image, the music does not overlap, the current playing halts and the most recent file -> play is done_

## Supporting Information
_Currently the music will continue to play when the image has been closed and will end either when it reaches the end of the song or when the program is closed through file -> close. This issue is most seen on the hiroshige.gif file in the images directory as the music played from this file is quite long._

**Comment by jody** [comment]
This "User Story" does not appear to presume a behavior that doesn't match with the current behavior (at least when tested on macOS). In particular, once the Play action is selected the picture windows do not respond to menu item requests. This also means that it is not currently possible to begin playing a second image at the same time (such as for a duet).

Perhaps there is an intent for multiple other changes to be inferred that would provide the context for this story. If so, please write those user stories explicitly. Then this user story might be added that will build on such a product.
