### ISSUE TITLE
[Bug] Program Cannot Be Closed When Music Is Playing

### ISSUE THREAD

**Issue by nicholasmatthews-dev** [MetroCS/imagelab#74]
**Describe the bug**
When play is selected from **file**>play, no open windows can be closed. 

**To Reproduce**
1. Go to 'File'
2. Click on 'Play'
3. Click on Close Window Button

**Expected behavior**
Windows should close and audio should stop.

**Desktop**
 - OS: Windows

**Comment by CamiJolly1** [comment]
I have the opposite issue. When playing an image, the music will still play when I close out of the image, the window, and the terminal window. The only way the music stops is when I terminate the program in BlueJ.

**Comment by jody** [comment]
> I have the opposite issue. When playing an image, the music will still play when I close out of the image, the window, and the terminal window. The only way the music stops is when I terminate the program in BlueJ.

@CamiJolly1 I agree with your assessment. Thank you for looking into this and helping triage the issue.

It is always possible to stop the executing process, which is running via an instance of the Java Virtual Machine (JVM).

This might be hinting at a user-experience _design_ issue defining what behavior should be expected from the product.

I will mark this as "working as designed" (meaning that there is no specification against which to file this as a bug) and close this issue.
