### ISSUE TITLE
[UserStory] Add Documentation Detailing Product Features

### ISSUE THREAD

**Issue by acohn93** [MetroCS/imagelab#75]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  developer or user
**I want**  a document that specifies the function of each feature in imagelab
**so that**  I can know what each feature is meant to do.

## Acceptance Criteria

1. Each feature has a detailed description of its function
2. It is easy for a user to understand how to use each feature

## Supporting Information
There is no existing description of imagelab features

Feature - A distinguishing characteristic of a system item (includes both functional and nonfunctional attributes such as performance and reusability).

source: "IEEE Standard for Software and System Test Documentation," in IEEE Std 829-2008 , vol., no., pp.1-150, 18 July 2008, doi: 10.1109/IEEESTD.2008.4578383.

**Comment by jody** [comment]
The use of the term, "features", is ambiguous in this context.

It would be beneficial to provide the intended definition along with a citation. For example, the definition of "feature" defined in [829-2008 - IEEE Standard for Software and System Test Documentation
](https://ieeexplore.ieee.org/document/4578383/definitions#definitions) is _"a distinguishing characteristic of a system item (includes both functional and nonfunctional attributes such as performance and reusability)"_.
