### ISSUE TITLE
[Bug] Issue running ImageLab on Linux using Java 11

### ISSUE THREAD

**Issue by ColinLouis95** [MetroCS/imagelab#79]
**Describe the bug**
When executing the java -jar imagelab.jar command on a Linux terminal running Java 11, a compile issue occurs stating that the user is missing a .so file in their Java file path. 
**To Reproduce**
1. Go to the system's terminal
2. Navigate to the ImageLab filepath
3. Enter in the command java -jar imagelab.jar
4. See error: 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so

**Expected behavior**
After running the command, the program should behave as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/57474778/137157920-d3da00b3-63a9-4370-9dbf-8268e98768a1.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04.3 LTS
 - OpenJDK 11

**Additional context**
This problem has been replicated on multiple Ubuntu 20.04.3 machines running Java 11.

**Comment by ColinLouis95** [comment]
Here is the output of the command:

openjdk-11-jdk-headless/focal-updates,focal-security,now 11.0.11+9-0ubuntu2~20.04 amd64 [installed]
openjdk-11-jre-headless/focal-updates,focal-security,now 11.0.11+9-0ubuntu2~20.04 amd64 [installed,automatic]
openjdk-17-jdk-headless/focal-updates,now 17+35-1~20.04 amd64 [installed,automatic]
openjdk-17-jdk/focal-updates,now 17+35-1~20.04 amd64 [installed]
openjdk-17-jre-headless/focal-updates,now 17+35-1~20.04 amd64 [installed,automatic]
openjdk-17-jre/focal-updates,now 17+35-1~20.04 amd64 [installed,automatic]

**Comment by jody** [comment]
Overall, this seems like it might make for a "documentation improvement" user story, rather than reflecting a bug in the product.  Consider what additional documentation would have been beneficial and where it might have been located.
