### ISSUE TITLE
[UserStory] Unit Test for DisplayImage

### ISSUE THREAD

**Issue by GracchusMinor** [MetroCS/imagelab#8]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer 
**I want**  a unit test for the DisplayImage class  
**so that**  I can identify that the class is performing correctly

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Unit Test covers 85% of executable code within DisplayImage.java
* Includes documentation for maintainers describing how to run and interpret tests

## Supporting Information
_(Relevant information, context, resources)_

Use JUnit framework

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_
 [Add unit tests for existing classes](https://github.com/MetroCS/imagelab/issues/4)

**Comment by jody** [comment]
I updated the outcome and the acceptance criteria to use correct naming and also to indicate the package within which the class resides.  (Added example of using a link to the referenced file in the acceptance criteria.)

What sort of "documentation for maintainers" is required?  In particular, is this specific to tests for DisplayImage.java or for the parent user story #4?

**Comment by GracchusMinor** [comment]
Please assign this issue to the following team and its members:
@MetroCS/efficientsoftwarehypothesis
@jstrelka
@GracchusMinor
@TImmyTurner123
@BlackCanyonDreams
@DendeLime

Thank you.

**Comment by jstrelka** [comment]
Please return issue to the TODO lane.

**Comment by nlaratta** [comment]
I'd like to be assigned to this issue, please.

**Comment by GOKU900** [comment]
I'd like to be assigned this issue.

**Comment by entrylevelcs** [comment]
I am part of GOKU900's group and would also like to be assigned to this issue.

**Comment by iglooghost** [comment]
I'm also a part of GOKU900's group and would like to be assigned

**Comment by nredwing** [comment]
I am also apart of guko's group and would like to be assigned.
