### ISSUE TITLE
[UserStory] Add Documentation on Java Version Dependency

### ISSUE THREAD

**Issue by Kelzihar** [MetroCS/imagelab#80]
# User Story
### Essential components
- [x] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  new user 
**I want**  to know what what version of java I need for building the latest version of imagelab
**so that**  imagelab runs in the way it was intended

## Acceptance Criteria

* Addition in the [README.md](https://github.com/MetroCS/imagelab/blob/master/README.md) on the version of java that is recommended for building imagelab

## Supporting Information
It was found that running imagelab gathered from [https://metrocs.github.io/imagelab/](https://metrocs.github.io/imagelab/) resulted in different actions with the play feature when compared to the current repository being built in java 11 and up. The play function in the default would prevent any actions being done while the music is playing, while in a java 11 build, actions could still be done while the play feature was occurring.

**Comment by jody** [comment]
Are "new users" building the latest version of imageLab?
One standard model for usage is for new users to build new filters and run them with an existing jar.

If they are building imageLab (such as by using BlueJ or another IDE), are there any specific dependencies on the version of Java? That is, does the version of Java prevent building a working version of imageLab?  (Although the specific behavior of imageLab may depend on the version of Java, unless those specific behaviors are documented for users there doesn't seem to be an issue here.)
