### ISSUE TITLE
[UserStory]  User doesn't want there to be a problem when canceling out of the save window.

### ISSUE THREAD

**Issue by am10nxw** [MetroCS/imagelab#81]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Student of cs3250 class.
**I want**  to be able to cancel out of saving an image without telling me that imageLab has "Encountered a problem in ImgProvider.save() - Please try again." .
**so that**  I know the program is running properly and I know I don't need to try again.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ When in the save image window if cancel is select the save image window closes without showing the error message "Encountered a problem in ImgProvider.save() - Please try again." , unless there is actually a problem and the user needs to try again.  
* 
### Scenario 1
**Given**  a user has opened an image in image lab, selected file > save and is looking at the save window
**when**  the user selects the cancel button
**then**  the user doesn't get an error saying "Encountered a problem in ImgProvider.save() - Please try again."

**Comment by jody** [comment]
> * _Rule 1_ When in the save image window if cancel is select **the program exits** without showing the error message "Encountered a problem in ImgProvider.save() - Please try again." , unless there is actually a problem and the user needs to try again.
(Emphasis added.)

This behavior seems contrary to the rationale, "I know the program is running properly and I know I don't need to try again."  It also doesn't seem to be a desired behavior for a "Student of cs3250 class".  Since these stakeholders in particular are accessible directly, it would be useful to poll them to see if most actually prefer the program to exit rather than to continue running.

**Comment by am10nxw** [comment]
I updated the rule by removing the program exists and adding the save image window 

> Rule 1 When in the save image window if cancel is select the **save image window closes** without showing the error message "Encountered a problem in ImgProvider.save() - Please try again." , unless there is actually a problem and the user needs to try again.
(Emphasis added.)
