### ISSUE TITLE
[UserStory] The play() function from ImgProvider should be in it's own class

### ISSUE THREAD

**Issue by sjohn330** [MetroCS/imagelab#82]
As a developer, I think that the ImgProvider class is doing too much, and that the music components in the play() class should be in it's own class. I want the play function of ImgProvider to be in it's own class without affecting the functionality of play() so that it is more maintainable.

Requirements:
1.) play() should be in it's own class
2.) the "play" option on the menu should continue to function

**Comment by jody** [comment]
Please resubmit using the User Story issue template.
