### ISSUE TITLE
Cannot Apply Filters to Image

### ISSUE THREAD

**Issue by lonespartan12** [MetroCS/imagelab#91]
**Describe the bug**
After selecting an image to modify, the imagelab filters menu bar does not function. It appears as if there are no options for filters to apply.

**To Reproduce**
1. Open imagelab
2. Select 'File' -> 'Open'
3. Select an image to apply a filter too.
4. Select 'Filter' menu item
5. nothing happens.

**Expected behavior**
After selecting the 'Filter' menu item, I am expecting to see a list of filters that I can apply to the image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu V21.01
 - Browser: Mozilla
 - Version10.13/2021
**Smartphone (please complete the following information):**

**Additional context**

**Comment by jody** [comment]
This is the expected behavior when there are no compiled filters in the "filters" directory.
