### ISSUE TITLE
[UserStory] UI Opens Images in Tabbed Frames

### ISSUE THREAD

**Issue by suprecam** [MetroCS/imagelab#92]
**User Story:**
UI Opens Images in Tabbed Frames

### Essential components
- [ ] Allow multiple images to be open simultaneously within the same window.
- [ ] Open images' UI containers are displayed as tabs located directly underneath the menu bar.
- [ ] One tab (the selected tab) is visible at a time.

## Story
**As a** customer (i.e. end-user of ImageLab)
**I want**  tabbed UI frames to help me stay better organized when using the product
**so that**  it is less cumbersome to work with more than one or two images at a time.

## Acceptance Criteria
* _Rule 1: Same look and feel as the rest of the application's UI._
* _Rule 2: Does not complicate the application's UI in any way._

### Scenario:
**Given**  _Opening an Image in the application_  
**when**  _Application has one user interface window_  
**then**  _application remains in single window with a new tab added, titled <image_file_name>, where <image_file_name> refers to the name of the image opened on the filesystem._  

## Supporting Information
From _User Interface Design Tips, Techniques, and Principles_ by Scott W. Ambler
"16. Don't create busy user interfaces..."
"17. Group things effectively..."
Source: Scott W. Ambler, Web: http://www.ambysoft.com/essays/userInterfaceDesign.html (Accessed 10/15/2021).

### Depends On
_None._
### Dependents
_None._

**Comment by jody** [comment]
Your thoughtful consideration of the user experience is very much appreciated!

A prominent workflow of imageLab involves users wanting to see content simultaneously, which is a contraindication for the use of tabs. Although some users may prefer tabbed contents to separate windows, changing the current design to use tabs may impair a primary expected use of imageLab: **comparing an image with filtered versions of that image.**

Here are quotes from two references that describe when the use of tabs is and is not appropriate from a user experience (UX) perspective.

- _"You should not use tabs in your designs when the user will need to compare several sections of content with each other."_
Interaction Design Foundation, "Embrace the Mental Models of Users by Implementing Tabs."
https://www.interaction-design.org/literature/article/embrace-the-mental-models-of-users-by-implementing-tabs

- _"Use tabs only when users don't need to see content from multiple tabs simultaneously. "_
Jakob Nielsen, "Tabs, Used Right."
https://www.nngroup.com/articles/tabs-used-right/

> Aside: The acceptance criteria appear to specify a particular solution implementation, which is inappropriate for a requirement specification. A user story and its acceptance criteria must address the objective but not constrain how the objective is implemented.
